const {
    createApp
} = Vue;

const app = createApp({
    data() {
        return {
            contenido: contenido,
            interruptor1: false,
            interruptor2: false,
            interruptor3: false,
            interruptor4: false,
            interruptor5: false,
            interruptor6: false,
            interruptor7: false,
            interruptor8: false,
            interruptor9: false,
            interruptor10: false,
            interruptor11: false,
            interruptor12: false,
            interruptor13: false,
            interruptor14: false,
            interruptor15: false,
            interruptor16: false,
            interruptor17: false,
            interruptor18: false,
            interruptor19: false,
            interruptor20: false,
            interruptor21: false,
            interruptor22: false,
            interruptor23: false,
            interruptor24: false,
            interruptor25: false,
            interruptor26: false,
            interruptor27: false,
            interruptor28: false,
            interruptor29: false,
            interruptor30: false,
            interruptor31: false,
            interruptor32: false,
            interruptor33: false,
            interruptor34: false,
            interruptor35: false,
            interruptor36: false,
            interruptor37: false,
            interruptor38: false,
            interruptor39: false,
            interruptor40: false,
            interruptor41: false,
            interruptor42: false,
            interruptor43: false,
            interruptor44: false,
            interruptor45: false,
            interruptor46: false,
            interruptor47: false,
            interruptor48: false,
            interruptor49: false,
            interruptor50: false,
            interruptor51: false,
            interruptor52: false,
            interruptor53: false,
            interruptor54: false,
            interruptor55: false,
            interruptor56: false,
            interruptor57: false,
            interruptor58: false,
            interruptor59: false,
            interruptor60: false,
            interruptor61: false,
            interruptor62: false,
            interruptor63: false,
            interruptor64: false,
            interruptor65: false,
            interruptor66: false,
            interruptor67: false,
            interruptor68: false,
            interruptor69: false,
            interruptor70: false,
            interruptor71: false,
            interruptor72: false,
            interruptor73: false,
            interruptor74: false,
            interruptor75: false,
            interruptor76: false,
            interruptor77: false,
            interruptor78: false,
            interruptor79: false,
            interruptor80: false,
            interruptor81: false,
            interruptor82: false,
            interruptor83: false,
            interruptor84: false,
            interruptor85: false,
            interruptor86: false,
            interruptor87: false,
            interruptor88: false,
            interruptor89: false,
            interruptor90: false,
            interruptor91: false,
            interruptor92: false,
            interruptor93: false,
            interruptor94: false,
            interruptor95: false,
            interruptor96: false,
            interruptor97: false,
            interruptor98: false,
            interruptor99: false,
            interruptor100: false,
            interruptor101: false,
            interruptor102: false,
            interruptor103: false,
            interruptor104: false,
            interruptor105: false,
            interruptor106: false,
            interruptor107: false,
            interruptor108: false,
            interruptor109: false,
            interruptor110: false,
            interruptor111: false,
            interruptor112: false,
            interruptor113: false,
            interruptor114: false,
            interruptor115: false,
            interruptor116: false,
            interruptor117: false,
            interruptor118: false,
            interruptor119: false,
            interruptor120: false,
            interruptor121: false,
            interruptor122: false,
            interruptor123: false,
            interruptor124: false,
            interruptor125: false,
            interruptor126: false,
            interruptor127: false,
            interruptor128: false,
            interruptor129: false,
            interruptor130: false,
            interruptor131: false,
            interruptor132: false,
            interruptor133: false,
            interruptor134: false,
            interruptor135: false,
            interruptor136: false,
            interruptor137: false,
            interruptor138: false,
            interruptor139: false,
            interruptor140: false,
            interruptor141: false,
            interruptor142: false,
            interruptor143: false,
            interruptor144: false,
            interruptor145: false,
            interruptor146: false,
            interruptor147: false,
            interruptor148: false,
            interruptor149: false,
            interruptor150: false,
            interruptor151: false,
            interruptor152: false,
            interruptor153: false,
            interruptor154: false,
            interruptor155: false,
            interruptor156: false,
            interruptor157: false,
            interruptor158: false,
            interruptor159: false,
            interruptor160: false,
            interruptor161: false,
            interruptor162: false,
            interruptor163: false,
            interruptor164: false,
            interruptor165: false,
            interruptor166: false,
            interruptor167: false,
            interruptor168: false,
            interruptor169: false,
            interruptor170: false,
            interruptor171: false,
            interruptor172: false,
            interruptor173: false,
            interruptor174: false,
            interruptor175: false,
            interruptor176: false,
            interruptor177: false,
            interruptor178: false,
            interruptor179: false,
            interruptor180: false,
            interruptor181: false,
            interruptor182: false,
            interruptor183: false,
            interruptor184: false,
            interruptor185: false,
            interruptor186: false,
            interruptor187: false,
            interruptor188: false,
            interruptor189: false,
            interruptor190: false,
            interruptor191: false,
            interruptor192: false,
            interruptor193: false,
            interruptor194: false,
            interruptor195: false,
            interruptor196: false,
            interruptor197: false,
            interruptor198: false,
            interruptor199: false,
            interruptor200: false,
            interruptor201: false,
            interruptor202: false,
            interruptor203: false,
            interruptor204: false,
            interruptor205: false,
            interruptor206: false,
            interruptor207: false,
            interruptor208: false,
            interruptor209: false,
            interruptor210: false,
            interruptor211: false,
            interruptor212: false,
            interruptor213: false,
            interruptor214: false,
            interruptor215: false,
            interruptor216: false,
            interruptor217: false,
            interruptor218: false,
            interruptor219: false,
            interruptor220: false,
            interruptor221: false,
            interruptor222: false,
            interruptor223: false,
            interruptor224: false,
            interruptor225: false,
            interruptor226: false,
            interruptor227: false,
            interruptor228: false,
            interruptor229: false,
            interruptor230: false,
            interruptor231: false,
            interruptor232: false,
            interruptor233: false,
            interruptor234: false,
            interruptor235: false,
            interruptor236: false,
            interruptor237: false,
        };
    },
    methods: {
        boton(numero) {
            if (numero <= 237) {
                this['interruptor' + numero] = !this['interruptor' + numero];
            }
        }
    }
});

app.mount("#app");

/*

else if (numero === 207) {
                this.interruptor207 = !this.interruptor207;

else if (numero <= 257) {
                this['interruptor' + numero] = !this['interruptor' + numero];
        }

buttonClasses() {
            return this.interruptor 
                ? 'bg-red-500 hover:bg-red-600 text-white' 
                : 'bg-green-500 hover:bg-green-600 text-white';
        },*/

/*contenidoExterno: contenidoExterno !== 'undefined' ? contenidoExterno : '<p>Contenido no disponible</p>'*/
/*contenidoExterno: contenidoExterno !== 'undefined' ? contenidoExterno : '<p>Contenido no disponible</p>'*/